config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resource :sessions, only: [:new, :create, :destroy]
  resources :users do
    resources :boardgames
  end
  resources :friendships, only: [:new, :create, :destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boardgame.rb
class Boardgame < ApplicationRecord
  belongs_to :owner, class_name: "User"
  validates :name, :description, :genre, :players, :play_time, presence: true

  def self.search(search)
    # get all usernames
    # from those usernames, make an array of relevant usernames based on search parameter
    all_usernames = Boardgame.first.owner.class.all.pluck(:username)
    username_search_results = []
    all_usernames.each do |user|
      if user.include?(search)
        username_search_results << user
      end
    end


    # get the games from the relevant usernames
    games_by_relevant_usernames = []
    username_search_results.each do |user|
      games_by_relevant_usernames << Boardgame.includes(:owner).where(:users => { username: user } ).all
    end

    games_by_relevant_usernames << where('name iLIKE :search OR genre iLIKE :search', search: "%#{search}%")
    return games_by_relevant_usernames[0]

  end

  def self.upload_to_s3(image)
    s3 = Aws::S3::Resource.new(region:'us-east-2')
    obj = s3.bucket('board-game-tracker').object(File.basename(image))
    obj.upload_file(image)
    obj.public_url
  end

  def self.friends_games(friends)
    friends_boardgame = []
    return nil if friends.empty?
    friends.each { |friend| friends_boardgame << friend.boardgames }
    friends_boardgame.flatten!
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"

  def self.fetch_friends(user)
    friendships = Friendship.accepted_friendships(user)
    friendships.map { |friendship| friendship.friend }
  end

  def self.accepted_friendships(user)
    user.friendships.select do |friendship|
      another_friendship = Friendship.find_by(user_id: friendship.friend_id, friend_id: friendship.user_id)
      friendship.accepted && another_friendship.accepted
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :boardgames, foreign_key: "owner_id"
  has_many :friendships
  has_many :friends, through: :friendships
  validates :password, :length => { :minimum => 4 }, on: :create
  validates :username, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/boardgames_controller.rb
class BoardgamesController < ApplicationController

  def index
    @all_usernames = User.all.pluck(:username)
    if logged_in?
      @user = User.find_by(id: params[:user_id])
      @friend_requests = @user.friendships.where(accepted: false)
      @friends = Friendship.fetch_friends(@user)

      # search method
      if params[:search]
        @search_results = Boardgame.search(params[:search])
        # @friends_games = Boardgame.search(params[:search]).where.not(owner_id: @user.id).order('created_at DESC')
      else
        @friends_games = Boardgame.friends_games(@friends)
      end
   else
      redirect_to root_path
    end
  end

  def new
    if logged_in?
      @boardgame = Boardgame.new
    else
      redirect_to root_path
    end
  end

  def create
    @boardgame = Boardgame.new(boardgame_params)
    if params[:boardgame][:image]
      @boardgame.image = Boardgame.upload_to_s3(params[:boardgame][:image].tempfile)
    end

    if @boardgame.save
      flash[:notice] = "#{@boardgame.name} was successfully saved"
      redirect_to user_boardgames_path(@boardgame.owner_id)
    else
      @errors = @boardgame.errors.full_messages
      render 'new'
    end
  end

  def show
    @boardgame = Boardgame.find_by(id: params[:id])
  end


  def edit
    if logged_in?
      @boardgame = Boardgame.find_by(id: params[:id])
      if session[:user_id] != @boardgame.owner_id
        flash[:alert] = "Can't edit another user game"
        redirect_to user_boardgames_path(@boardgame.owner_id)
      end
    else
      redirect_to root_path
    end
  end

  def update
    @boardgame = Boardgame.find_by(id: params[:id])
    @boardgame.image = params[:boardgame][:image]
    if @boardgame.image.include?("Http")
      @boardgame.image = Boardgame.upload_to_s3(params[:boardgame][:image].tempfile)
    end

    if @boardgame.update(boardgame_params)
      flash[:notice] = "#{@boardgame.name} was successfully updated"
      redirect_to user_boardgames_path(@boardgame.owner_id)
    else
      @errors = @boardgame.errors.full_messages
      render :edit
    end
  end

  def destroy
    @boardgame = Boardgame.find(params[:id])
    @boardgame.destroy
    flash[:notice] = "#{@boardgame} was successfully deleted"
    redirect_to user_boardgames_path
  end

  private

  def boardgame_params
    params.require(:boardgame).permit(:name, :description, :genre,:play_time, :players, :owner_id)
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def new
  end

  def create
    friend_id = params[:friendships][:friend_id]
    # add validation if already friends
    Friendship.create(friend_id: friend_id, user_id: current_user.id, accepted: true)
    Friendship.create(friend_id: current_user.id, user_id: friend_id)
    flash[:notice] = "Friend request sent"
    redirect_to user_boardgames_path(friend_id)
  end

  def update
    @friendship = Friendship.find(params[:id])
    @friendship.update(accepted: true)
    flash[:notice] = "You became #{@friendship.friend.username}'s friend"
    redirect_to user_boardgames_path(current_user.id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # find current user by session id
    @user = User.find_by(id: session[:user_id])

    if logged_in?
      redirect_to user_boardgames_path(@user.id)
    end
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      login(@user)
      flash[:notice] = "Welecome back #{@user.username}!"
      redirect_to user_boardgames_path(@user.id)
    else
      @errors = ["Username and/or password is incorrect. Please try again."]
      render :new
    end
  end

  def destroy
    logout
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      flash[:notice] = "Welecome #{@user.username}!"
      redirect_to user_boardgames_path(@user.id)
    else
      @errors = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def show
      @user = User.find(params[:id])
      if logged_in?
        redirect_to @user
      else
        redirect_to root_path
      end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session.delete(:user_id)
  end

  def logged_in?
    if session[:user_id] != nil
      true
    else
      false
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if logged_in?
  end

  def page_belongs_to_user?
    return true if @user.id == session[:user_id]
    false
  end

end

app/views/boardgames/_form.html.erb
<%= render "layouts/errors" %>
<div class="form-div">
  <%= form_with local: true, model: [current_user, @boardgame] do |f| %>
    <%= hidden_field(:boardgame, :owner_id, value: current_user.id) %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :description %><br>
    <%= f.text_field :description %><br>
    <%= f.label :genre %><br>
    <%= f.text_field :genre %><br>
    <%= f.label :play_time %><br>
    <%= f.text_field :play_time %><br>
    <%= f.label :players %><br>
    <%= f.text_field :players %><br>
    <%= f.label :image %><br>
    <%= f.file_field :image %><br>
    <%= f.submit %>
  <% end %>

</div>

app/views/boardgames/_logout.html.erb
<% if logged_in? %>
    <%= link_to 'Logout', sessions_path, method: 'delete' %>
<% end %>

app/views/boardgames/edit.html.erb
<h1>Edit <%= @boardgame.name %></h1>

<%= render 'form' %>

app/views/boardgames/index.html.erb
<%= form_tag(user_boardgames_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Boardgames" %>
  <%= submit_tag "Search" %>
<% end %>

  <%= link_to "Add a Boardgame", new_user_boardgame_path(@user.id) %>

<h1><%=@user.username.capitalize%>'s Page</h1>

<% if page_belongs_to_user? %>
  <div id="friend-list">
    <div>
      <h3>Friend Requests</h3>
      <ul>
        <% @friend_requests.each do |friend_request| %>
          <%= form_with local: true, method: 'patch', url: friendship_path(friend_request.id) do |f| %>
            <%= f.submit "Accept #{friend_request.friend.username}'s request" %>
          <% end %>
        <% end %>
      </ul>
    </div>

    <div>
      <h3>Friends:</h3>
      <ul>
        <% @friends.each do |friend| %>
          <li><%= friend.username %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>



<% if !current_user.friends.find_by(id: @user.id) && !page_belongs_to_user? %>
  <%= form_with local: true, url: friendships_path do |f| %>
    <%= hidden_field(:friendships, :friend_id, value: @user.id) %>
    <%= f.submit "Add Friend" %>
  <% end %>
<% end %>

<% if @user.boardgames %>
  <h2><%=@user.username.capitalize%>'s Boardgames</h2>
  <ul>
    <% @user.boardgames.each do |game| %>
    <li><%= link_to(game.name, user_boardgame_path(@user.id, game.id),class: :gname) %></li>
    <% if page_belongs_to_user? %>
      <li><%= link_to('Edit', edit_user_boardgame_path(@user.id, game.id)) %> | <%= link_to('Delete', user_boardgame_path(@user.id, game.id), method: 'delete') %></li>
    <% end %>
    <li><%= image_tag(game.image) %></li>
    <% end %>
  </ul>
<% end %>
<br>


<% if @search_results %>
  <h2>Search Results:</h2>
  <ul>
    <% @search_results.each do |game| %>
      <li><%= link_to(game.name, user_boardgame_path(game.owner_id, game.id),class: :gname) %></li>
      <li><%= image_tag(game.image) %></li>
      <li class="g-owner">Owned by <%= link_to "#{game.owner.username}", user_boardgames_path(game.owner_id) %></li>
    <% end %>
  </ul>
<% else %>
  <h2>Friend's Boardgames</h2>
  <% if @friends_games %>
    <ul>
      <% @friends_games.each do |game| %>
        <li><%= link_to(game.name, user_boardgame_path(game.owner_id, game.id),class: :gname) %></li>
        <li><%= image_tag(game.image) %></li>
        <li class="g-owner">Owned by <%= link_to "#{game.owner.username}", user_boardgames_path(game.owner_id) %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/boardgames/new.html.erb
<h1>Add a Boardgame</h1>

<%= render 'form' %>

app/views/boardgames/show.html.erb
<h1><%= @boardgame.name %></h1>

<div>
  <p>Description:</p>
  <p><%= @boardgame.description %></p>
</div>
<div>
  <p>Genre:</p>
  <p><%= @boardgame.genre %></p>
</div>
<div>
  <p>Total Players:</p>
  <p><%= @boardgame.players %></p>
</div>
<div>
  <p>Owner:</p>
  <p><%= @boardgame.owner.username %></p>
</div>

app/views/layouts/_errors.html.erb
<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_logout.html.erb
<% if logged_in? %>
    <%= link_to 'Logout', sessions_path, method: 'delete' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardgameTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="topbar">
    <h1>Golden Bear Board Games</h1>
    <%= link_to('Home', root_path) %>
    <%= render "layouts/logout" %>
  </div>
  <div id="flash">
    <% if flash[:notice] %>
      <div class="notice">
        <%= link_to flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
        <div class="alert">
          <%= link_to flash[:alert] %>
        </div>
    <% end %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Create a new account</h1>

<%= render "layouts/errors" %>
<div class="form-div">
<%= form_with model: @user, class: 'centered-form' do |f| %>
  <%=f.label :username%>
  <%= f.text_field :username %>
  <%=f.label :password%>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>
</div>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>
<%= render partial: "logout" %>